### ISSUE TITLE
SOVAP crashes in step 3 (MegaHit assembly)

### ISSUE THREAD

**Issue by jllavin77** [poursalavati/SOVAP#1]
Dear Developers,
First I want to thank you for the effort you made creating SOVAP and facilitating virome analysis to novices in the field like me.
I am writing you this e-mail to ask you about a problem I've had while running SOVAP.
After the installation, I tested it with a paired-end sample which reads  where in .fq.gz format (zipped), and SOVAP wasn't able to run
MegaHit on them.
I run this command (all the independent programs run correctly with those paths to their respective databases):

`python ./Run_SOVAP_JL.py -r1 /storage/GPRNA_1.fastq.gz -r2 /storage/GPRNA_2.fastq.gz -t 12 -x /storage/DBs/centrifuge/hvc -g /storage/DBs/genomad_db/ -d /storage/DBs/IMGv4/IMGv4.dmnd --end_to_end`

And the megahit.stderr.log showed the following error:

`2024-09-02 13:12:30 - MEGAHIT v1.2.9
2024-09-02 13:12:31 - Using megahit_core with POPCNT and BMI2 support
Traceback (most recent call last):
  File "/root/miniconda3/envs/SOVAP/bin/megahit", line 1038, in <module>
    main()
  File "/root/miniconda3/envs/SOVAP/bin/megahit", line 988, in main
    build_library()
  File "/root/miniconda3/envs/SOVAP/bin/megahit", line 264, in checked_or_call
    func(*args, **kwargs)
  File "/root/miniconda3/envs/SOVAP/bin/megahit", line 723, in build_library
    create_fifo('pe1', i, inpipe_cmd(opt.pe1[i]))
  File "/root/miniconda3/envs/SOVAP/bin/megahit", line 710, in create_fifo
    os.mkfifo(fifo_path)
OSError: [Errno 5] Input/output error: '/storage/downloads/SOVAP/3_Megahit_Output/tmp/inpipe.pe1.0'`

Then, I decided to look at the code of Run_SOVAP.py and try to run Megahit independently with the same parameters you specify  there:

`megahit -1 {input_file1} -2 {input_file2} -r {input_file3} --presets meta-large -o 3_Megahit_Output -t {threads} --min-contig-len 150`

Later, I copied the results into the folder  "3_Megahit_Output" and re-run SOVAP, which resulted in the complete analysis, yielding correct results.

My question is, have you ever experienced this problem?  May it be due to the zipped format of the input that may crash the  MegaHit step? Am I missing something simple that I'm unable to notice?

Thanks in advance.
JL

`

**Comment by poursalavati** [comment]
Thank you for reaching out and for using SOVAP! We greatly appreciate your feedback.  

Based on the error message you provided, it appears that the main issue is related to creating a FIFO file during the MEGAHIT step of the pipeline. Specifically, the error occurs when trying to create this file:

`/storage/downloads/SOVAP/3_Megahit_Output/tmp/inpipe.pe1.0`

This type of error (OSError: [Errno 5] Input/output error) often indicates a low-level issue with the file system. Here are some potential causes to considr:

- File System Permissions: 
   The process might not have the necessary permissions to create files in the output directory. Pls check the permissions of the `/storage/downloads/SOVAP/3_Megahit_Output/tmp/` directory and ensure the user running the pipeline has full permissions to the destination location.

- File System Issues: 
   There could be problems with the file system where the output directory is located. This could include the file system being full, read-only, or corrupted, as well as issues with network-mounted file systems (e.g., QNAP if applicable).

- Quota Limit (If running on a shared or cluster environment)  

Given that MEGAHIT works when run standalone, the most likely causes are:

- Different permissions or ownership when run through the pipeline vs. manually
- File system mount issues
- Quota or resource limits

To troubleshoot this issue, I recommend the following steps:

1. Check the permissions and ownership of the `/storage/downloads/SOVAP/3_Megahit_Output/tmp/` directory.
2. Verify the file system's health and available space.
3. If it's a network file system, check its connectivity and mounting status.
4. Review any quota limits that might be in place.
5. Consider running the pipeline with elevated permissions (if appropriate and safe to do so) to rule out permission issues.
6. Check system logs for any file system or I/O errors occurring around the time of the MEGAHIT run.

Regarding the input files, MEGAHIT should be able to handle gzipped input files without issues, so this is likely not the root cause. Please make sure you're using the same input files for the standalone MEGAHIT run as the ones used in the pipeline, which should be the output from the centrifuge step.

Additionally, try running both the pipeline and the standalone MEGAHIT in the same storage and possibly in the same folder of `3_Megahit_Output`. This will help rule out any permission or file system issues that might be specific to the location.

Hope these suggestions help. In the near future, a new SOVAP update will be released that includes additional tools and features, such as the ability to select different assemblers!  

As a tip, to speed up troubleshooting, I recommend trying the pipeline with a smaller test dataset. This can help isolate the issue more quickly.  

Naser
